# Generated by Django 4.1.3 on 2022-12-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailpage', '0003_productmodel_product_image_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
