# Generated by Django 4.1.3 on 2022-12-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailpage', '0005_primarycategorymodel_secondarycategorymodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secondarycategorymodel',
            options={'verbose_name': 'Secondary Category', 'verbose_name_plural': 'Secondary Categories'},
        ),
    ]
