# Generated by Django 4.1.3 on 2022-12-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailpage', '0006_alter_secondarycategorymodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarycategorymodel',
            name='category_header',
            field=models.ImageField(null=True, upload_to='category'),
        ),
    ]
