# Generated by Django 4.1.3 on 2022-12-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageimage',
            name='hpimage',
            field=models.ImageField(null='true', upload_to='homepage_image'),
            preserve_default='true',
        ),
    ]
